--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FlynnKunz/StaffMenuUI
build-by-default: true
branches:
- main
projects:
  StaffMenuUI:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version:  ^3.0.0
        branch: PM4
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.0.1
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.0.0
      - src: muqsit/InvMenu/InvMenu
        version: ^4.3.8
        branch: "4.0"
    lint:
      phpstan: false
...
